version: 2

jobs:
  checkout:
    docker:
      - image: node:8.6.0
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - ./*

  upload:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Connect to Big Query
          command: bash .circleci/bigquery-connect.sh
      - run:
          name: Upload to Big Query
          command: |
            bash .circleci/bigquery-load.sh funda.koop funda/koop_utrecht_houses.json
            bash .circleci/bigquery-load.sh funda.koop funda/koop_amersfoort_houses.json
            bash .circleci/bigquery-load.sh funda.koop funda/koop_hilversum_houses.json
            bash .circleci/bigquery-load.sh funda.koop funda/koop_amsterdam_houses.json
            bash .circleci/bigquery-load.sh funda.koop funda/koop_eindhoven_houses.json
            bash .circleci/bigquery-load.sh funda.koop funda/koop_rotterdam_houses.json

            bash .circleci/bigquery-load.sh funda.huur huizenzoeker/huur_utrecht_houses.json
            bash .circleci/bigquery-load.sh funda.huur huizenzoeker/huur_amersfoort_houses.json
            bash .circleci/bigquery-load.sh funda.huur huizenzoeker/huur_hilversum_houses.json
            bash .circleci/bigquery-load.sh funda.huur huizenzoeker/huur_amsterdam_houses.json
            bash .circleci/bigquery-load.sh funda.huur huizenzoeker/huur_eindhoven_houses.json
            bash .circleci/bigquery-load.sh funda.huur huizenzoeker/huur_rotterdam_houses.json

  funda:
    docker:
      - image: cypress/base:8
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install Cypress
          working_directory: funda
          command: npm install
      - run:
          name: Install Server
          working_directory: funda/server
          command: npm install
      - run:
          name: Gather data
          working_directory: funda
          command: |
            ./run.sh koop utrecht
            ./run.sh koop amersfoort
            ./run.sh koop hilversum
            ./run.sh koop amsterdam
            ./run.sh koop eindhoven
            ./run.sh koop rotterdam
      - persist_to_workspace:
          root: ~/
          paths:
            - ./project/funda/*.json

  huizenzoeker:
    docker:
      - image: python:3.6.4
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install Scrapy
          working_directory: huizenzoeker
          command: |
            pip install scrapy
      - run:
          name: Gather data
          working_directory: huizenzoeker
          command: |
            scrapy crawl huizenzoeker_spider -a place=utrecht    -a province=utrecht       -o huur_utrecht_houses.json -t jsonlines
            scrapy crawl huizenzoeker_spider -a place=amersfoort -a province=utrecht       -o huur_amersfoort_houses.json -t jsonlines
            scrapy crawl huizenzoeker_spider -a place=hilversum  -a province=noord-holland -o huur_hilversum_houses.json -t jsonlines
            scrapy crawl huizenzoeker_spider -a place=amsterdam  -a province=noord-holland -o huur_amsterdam_houses.json -t jsonlines
            scrapy crawl huizenzoeker_spider -a place=eindhoven  -a province=noord-brabant -o huur_eindhoven_houses.json -t jsonlines
            scrapy crawl huizenzoeker_spider -a place=rotterdam  -a province=zuid-holland  -o huur_rotterdam_houses.json -t jsonlines
      - run:
          name: Send data to big query
          working_directory: huizenzoeker
          command: |
            cat huur_utrecht_houses.json
      - persist_to_workspace:
          root: ~/
          paths:
            - ./project/huizenzoeker/*.json

workflows:
  version: 2
  commit:
    jobs:
      - checkout
      - funda:
          requires:
            - checkout
      - huizenzoeker:
          requires:
            - checkout
      - upload:
          requires:
            - funda
            - huizenzoeker

  nightly:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - checkout
      - funda:
          requires:
            - checkout
      - huizenzoeker:
          requires:
            - checkout
      - upload:
          requires:
            - funda
            - huizenzoeker