version: 2

jobs:
  checkout:
    docker:
      - image: node:8.6.0
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - ./*

  upload:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Upload to Big Query
          command: bash .circleci/bigquery.sh

  funda:
    docker:
      - image: cypress/base:8
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install Cypress
          working_directory: funda
          command: npm install
      - run:
          name: Install Server
          working_directory: funda/server
          command: npm install
      - run:
          name: Gather data
          working_directory: funda
          command: |
            ./run.sh koop utrecht
      - run:
          name: Send data to big query
          working_directory: funda
          command: |
            cat koop_utrecht_houses.json
      - persist_to_workspace:
          root: ~/
          paths:
            - ./funda/koop_utrecht_houses.json

  huizenzoeker:
    docker:
      - image: python:3.6.4
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install Scrapy
          working_directory: huizenzoeker
          command: |
            pip install scrapy
      - run:
          name: Gather data
          working_directory: huizenzoeker
          command: |
            scrapy crawl huizenzoeker_spider -a place=utrecht -o huur_utrecht_houses.json -t jsonlines
      - run:
          name: Send data to big query
          working_directory: huizenzoeker
          command: |
            cat huur_utrecht_houses.json
      -

workflows:
  version: 2
  commit:
    jobs:
      - checkout
      - funda:
          requires:
            - checkout
      - upload:
          requires:
            - funda


#      - huizenzoeker:
#          requires:
#            - checkout